controller_manager:
  ros__parameters:
    update_rate: 250

mit_controller:
  ros__parameters:
    joints:
      - hip_joint
      - big_leg_joint
      - thigh_joint
    mode: sim_effort_pd
    command_topic: /motor_cmd
    publish_feedback: true
    feedback_topic: /motor_feedback
    command_timeout_ms: 1500
    feedback_rate_hz: 20.0
