test_controller:
  ros__parameters:
    joints:
      - fl_hip_joint
      - fl_thigh_joint
      # ... 其他 10 个关节
    imu_name: "imu_sensor"
    contact_names: ["fl_foot", "fr_foot", "rl_foot", "rr_foot"]

controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    hw_params:
      is_sim: true
      delay: 0.009 # 仿真通信延迟，单位秒
    imu_params:
      accel:
        variance: 0.01       # 测量协方差
        bias_mean: 0.0       # 静态偏置，模拟真机安装/芯片误差
      gyro:
        variance: 0.0004
        bias_mean: 0.0
      orientation:
        variance: 0.0012
        
    test_controller:
      type: dog_controllers/DogTestController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

joint_state_broadcaster:
  ros__parameters:
    joints:
      - FL_HipX_joint
      - FL_HipY_joint
      - FL_Knee_joint
      - FR_HipX_joint
      - FR_HipY_joint
      - FR_Knee_joint
      - HL_HipX_joint
      - HL_HipY_joint
      - HL_Knee_joint
      - HR_HipX_joint
      - HR_HipY_joint
      - HR_Knee_joint

effort_controller:
  ros__parameters:
    joints:
      - FL_HipX_joint
      - FL_HipY_joint
      - FL_Knee_joint
      - FR_HipX_joint
      - FR_HipY_joint
      - FR_Knee_joint
      - HL_HipX_joint
      - HL_HipY_joint
      - HL_Knee_joint
      - HR_HipX_joint
      - HR_HipY_joint
      - HR_Knee_joint
    interface_name: effort
    
imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link